log:
  level: warn
  file: ''

plugin:

  ################# 服务插件 ################

  # 启动服务器的插件
  - tag: main_server
    type: server
    args:
      entry:
        - _no_ecs
        - lazy_cache      # 启用缓存
        - main_sequence   # 分流逻辑
      server:             # 服务器监听地址与协议。
        - protocol: udp
          addr: 127.0.0.1:5335
        - protocol: tcp
          addr: 127.0.0.1:5335

  ################# 可执行插件 ################

  # 包含分流的逻辑的插件
  - tag: main_sequence
    type: sequence
    args:
      exec:
        - if_and:
            - '!query_is_local_domain'
            - _qtype_AAAA           # 如果请求的 AAAA (ipv6) 类型
          exec:
            - _block_with_empty_response  # 用空白应答屏蔽
            - _end

        - if:
            - query_is_local_domain   # 已知的本地域名
            - '!_query_is_common'     # 和不常见的请求类型
          exec:
            - forward_local           # 用本地服务器
            - if:
                - response_has_local_ip
              exec:
                - _end

        - primary:
            - forward_local
            - if:
                - '!response_has_local_ip'
              exec:
                - _drop_response
          secondary:
            - forward_remote
            - if:
                - '!response_has_local_ip'
              exec:
                - blacklist
          fast_fallback: 200  # 这里建议设置成 local 服务器正常延时的 2~5 倍。
                              # 这个延时保证了 local 延时偶尔变高时，其结果不会被 remote 抢答。
                              # 如果 local 超过这个延时还没响应，可以假设 local 出现了问题。
                              # 这时用就采用 remote 的应答。
          always_standby: true


  # 转发请求至本地服务器的插件
  - tag: forward_local
    type: fast_forward
    args:
      upstream:
        - addr: '119.29.29.29'

  # 转发请求至远程服务器的插件
  - tag: forward_remote
    type: fast_forward
    args:
      upstream:
        - addr: 'tcp://1.1.1.1'
          idle_timeout: 90

  ################ 匹配器插件 #################

  # 匹配本地域名的插件
  - tag: query_is_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:cn'

  # 匹配非本地域名的插件
  - tag: query_is_non_local_domain
    type: query_matcher
    args:
      domain:
        - 'ext:./geosite.dat:geolocation-!cn'

  # 匹配本地 IP 的插件
  - tag: response_has_local_ip
    type: response_matcher
    args:
      ip:
        - 'ext:./geoip.dat:cn'

  - tag: blacklist
    type: 'ipset'
    args:
      set_name4: 'blacklist'   # 如果非空，存放 ipv4 地址到这个表。这个表属性 family 需为 `inet`。
      set_name6: ''   # 如果非空，存放 ipv6 地址到这个表。这个表属性 family 需为 `inet6`。
      mask4: 24       # 写入 ipv4 地址时使用的掩码。默认: 24。
      mask6: 32       # 写入 ipv6 地址时使用的掩码。默认: 32。

  - tag: lazy_cache
    type: 'cache'
    args:
      size: 10240
      lazy_cache_ttl: 1800
      lazy_cache_reply_ttl: 30

  - tag: 'real_ecs'
    type: 'ecs'
    args:
      auto: false             # 是否自动将客户端请求的来源地址作为 ECS 附加到请求。如果为 true，则预设地址不会被使用。
                              # 仅适用于公网的服务器。本地运行不要启用这个功能。
      ipv4: '255.255.255.255' # 预设的 IPv4 地址。会优先附加在 A 请求里。
      ipv6: 'ff00::'          # 预设的 IPv6 地址。会优先附加在 AAAA 请求里。
      force_overwrite: false  # 如果请求已有 ECS，是否强制覆盖。
      mask4: 24               # 用于 ipv4 地址的掩码。默认: 24。
      mask6: 48               # 用于 ipv6 地址的掩码。默认: 48。
